name: Initialize Production Server

on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USER }}
          password: ${{ secrets.PROD_SSH_PASS }}
          script: |
            cd ~
            git clone https://github.com/${{ github.repository }} .
            git checkout production
            php8.2 -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php8.2 composer-setup.php
            rm composer-setup.php
            php8.2 composer.phar install --no-dev --optimize-autoloader
