name: Deploy to Production

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SSH_HOST }}
          port: ${{ secrets.PROD_SSH_PORT }}
          username: ${{ secrets.PROD_SSH_USER }}
          password: ${{ secrets.PROD_SSH_PASS }}
          script: |
            cd ~/html
            git pull origin production
            php8.2 ~/composer.phar install --no-dev --optimize-autoloader --working-dir=/data/web/e140950/html
